# Numpy Examples

In [2]:
import numpy as np

### Creating arrays

In [8]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(2, 11)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [21]:
n = np.linspace(0, 1, 11)
n

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [19]:
n[2]

np.float64(0.2)

In [21]:
n[2] = 0.22
n

array([0.  , 0.1 , 0.22, 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 1.  ])

### Multidimensional array

In [23]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)

n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n[1, 2]

np.int64(6)

In [30]:
n[1, 2] = 100
n

array([[  1,   2,   3],
       [  4,   5, 100],
       [  7,   8,   9]])

In [32]:
n[2]

array([7, 8, 9])

In [36]:
n[2] = [2,2,2]

In [37]:
n

array([[  1,   2,   3],
       [  4,   5, 100],
       [  2,   2,   2]])

In [38]:
n[:,2]

array([  3, 100,   2])

In [39]:
n[:,2] = [1,1,1]

In [40]:
n

array([[1, 2, 1],
       [4, 5, 1],
       [2, 2, 1]])

### Randomly generated array

In [19]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [20]:
np.random.seed(2)
np.random.randint(low=0,high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element wise operation

In [27]:
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
n + 2

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [29]:
n * 3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [30]:
n / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

### Comparison Operation

In [32]:
n[n > 5]

array([6, 7, 8, 9])

In [33]:
n > 4

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

### Summarizing operations

In [34]:
n.min()

np.int64(1)

In [35]:
n.max()

np.int64(9)

In [36]:
n.mean()

np.float64(5.0)

In [37]:
n.sum()

np.int64(45)

In [38]:
n.std()

np.float64(2.581988897471611)