# Machine Learning Zoomcamp
## 1.8 Linear algebra refresher
#### Plan:

- Vector operations
- Multiplication
    - Vector-vector multiplication
    - Matrix-vector multiplication
    - Matrix-matrix multiplication
- Identity matrix
- Inverse

In [1]:
import numpy as np

### Vector Operation

In [3]:
u = np.array([2, 4, 1, 6])
u

array([2, 4, 1, 6])

In [4]:
v = np.array([1, 0, 0, 2])
v

array([1, 0, 0, 2])

In [5]:
2 * u

array([ 4,  8,  2, 12])

In [6]:
u + v

array([3, 4, 1, 8])

In [7]:
u * v

array([ 2,  0,  0, 12])

### Multiplicatioin

In [9]:
v.shape

(4,)

In [12]:
def vector_vector_multiplication(u, v): 
    assert u.shape[0] == v.shape[0]

    result = 0
    n = u.shape[0]
    for i in range(n):
        result = result + (u[i] * v[i])

    return result

In [13]:
vector_vector_multiplication(u, v)

np.int64(14)

In [15]:
v.dot(u) # using numpy function

np.int64(14)

In [17]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [19]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [20]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [21]:
U.dot(v) # using numpy funciton

array([14,  5,  5])

In [24]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
    [2, 1, 0],
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [27]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        Vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, Vi)
        result[:, i] = Uvi
    return result

In [28]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [29]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [31]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [34]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Inverse Matrix

In [38]:
Vs = V[[1,2,3]] # Square matrix
Vs

array([[0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [40]:

Vs_inv = np.linalg.inv(Vs) # Inverse of matrix
Vs_inv

array([[ 0.33333333, -0.33333333,  0.5       ],
       [-0.66666667,  0.66666667,  0.        ],
       [ 1.33333333, -0.33333333,  0.        ]])

In [42]:
Vs.dot(Vs_inv) # multiplication of matrix with its inverse will result identity matix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])